name: Deploy to shinyapps.io

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger
  
env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  TELRAAM_KEY: ${{ secrets.TELRAAM_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R environment
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 4.x
        
    - name: Setup dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::devtools
    
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev

    - name: Install R packages
      run: Rscript install-packages-deploy.R

    - name: Deploy to shinyapps.io
      run: |
        Rscript -e "rsconnect::setAccountInfo(name='agistaterre', token=${{secrets.SHINY_TOKEN}}, secret=${{secrets.SHINY_SECRET}})"
        Rscript -e "rsconnect::deployApp(appName = 'mov-around')" 
